CREATE DATABASE Proyecto_FinalDB
GO

USE Proyecto_FinalDB

GO

CREATE TABLE USUARIO 
(
ID INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
NOMBRE VARCHAR (50) NOT NULL,
APELLIDO VARCHAR (50) NOT NULL,
CORREO NVARCHAR (50) NOT NULL,
NOMBRE_USUARIO NVARCHAR (50) NOT NULL,
CONTRASENA NVARCHAR (50) NOT NULL,
ID_TIPO_USUARIO INT NOT NULL
)

GO

CREATE TABLE TIPO_USUARIO
(
ID INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
NOMBRE VARCHAR (20) NOT NULL
)

GO

CREATE TABLE PACIENTE
(
ID INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
NOMBRE VARCHAR (50) NOT NULL,
APELLIDO VARCHAR (50) NOT NULL,
TELEFONO NVARCHAR (20) NOT NULL,
DIRECCION NVARCHAR (100) NOT NULL,
CEDULA NVARCHAR (25) NOT NULL,
FECHA_NACIMIENTO DATE NOT NULL,
FUMADOR VARCHAR (5) NOT NULL,
ALERGIAS VARCHAR (5) NOT NULL,
FOTO NVARCHAR (200) NOT NULL
)

GO

CREATE TABLE MEDICOS 
(
ID INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
NOMBRE VARCHAR (50) NOT NULL,
APELLIDO VARCHAR (50) NOT NULL,
CORREO NVARCHAR (50) NOT NULL,
TELEFONO NVARCHAR (20) NOT NULL,
CEDULA NVARCHAR (20) NOT NULL,
FOTO NVARCHAR (MAX)
)

DROP TABLE MEDICOS

GO

CREATE TABLE CITAS
(
ID INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
ID_PACIENTE INT NOT NULL,
ID_MEDICO INT NOT NULL,
FECHA DATE NOT NULL,
HORA TIME NOT NULL,
CAUSA NVARCHAR (200) NOT NULL,
ID_ESTADO INT NOT NULL 
)

GO

CREATE TABLE ESTADO_CITAS
(
ID INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
ESTADO VARCHAR (30) NOT NULL
)

GO

CREATE TABLE ESTADO_PRUEBA
(
ID INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
ESTADO VARCHAR (20) NOT NULL
)

GO

CREATE TABLE RESULTADOS
(
ID INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
ID_PACIENTE INT NOT NULL,
ID_CITA INT NOT NULL,
ID_PRUEBA INT NOT NULL,
ID_DOCTOR INT NOT NULL,
RESULTADO NVARCHAR (100) NOT NULL,
ID_ESTADO INT NOT NULL
)

CREATE TABLE PRUEBAS_LABORATORIO
(
ID INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
NOMBRE NVARCHAR (70) NOT NULL
)
